# These are supported funding model platforms

#github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: BlackBeltPanda
#ko_fi: # Replace with a single Ko-fi username
custom: ["https://paypal.me/PandaCraftNetwork", "https://www.youtube.com/user/TheBlackBeltPanda/join"]
