# These are supported funding model platforms

github: BlackBeltPanda
patreon: BlackBeltPanda
#ko_fi: # Replace with a single Ko-fi username
custom: ["https://paypal.me/PandaCraftNetwork", "https://www.youtube.com/user/TheBlackBeltPanda/join"]
